export const techs = Object.freeze({
    HTML: Symbol("HTML"),
    CANVAS: Symbol("Canvas"),
    CSS: Symbol("CSS"),
    JAVASCRIPT: Symbol("JavaScript"),
    TYPESCRIPT: Symbol("TypeScript"),
    JAVA: Symbol("Java"),
    SPRING_BOOT: Symbol("Spring Boot"),
    NODE_JS: Symbol("Node.js"),
    EXPRESS: Symbol("Express.js"),
    SOCKET_IO: Symbol("Socket.io"),
    GIT: Symbol("Git"),
    ANGULAR: Symbol("Angular"),
    REACT: Symbol("React"),
    NEXT_JS: Symbol("Next.js"),
    AUTH_JS: Symbol("Auth.js"),
    ASTRO: Symbol("Astro"),
    TAILWIND: Symbol("Tailwind"),
    MYSQL: Symbol("MySQL"),
    POSTGRESQL: Symbol("PostgreSQL"),
    SQLITE: Symbol("SQLite"),
    SEQUELIZE: Symbol("Sequelize"),
    PRISMA: Symbol("Prisma"),
    JWE_TOKENS: Symbol("JWE Tokens"),
    JWT: Symbol("JWT"),
    BCRYPT: Symbol("bcrypt"),
    HOOK_FORM: Symbol("React Hook Form"),
    FIREBASE_STORAGE: Symbol("Firebase Storage"),
    ZOD: Symbol("Zod"),
    JOI: Symbol("Joi"),
});